title: Singapore Road Safety Council
url: https://www.srsc.org.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#cb333b"
  secondary-color: "#fe5000"
  media-colors:
    - title: media-color-one
      color: "#ffffff"
    - title: media-color-two
      color: "#cb333b"
    - title: media-color-three
      color: "#fe5000"
    - title: media-color-four
      color: "#ffffff"
    - title: media-color-five
      color: "#ffffff"
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.du295aw3abox.amplifyapp.com
prod: https://master.du295aw3abox.amplifyapp.com
shareicon: ""
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
